name: Gitcook CI
run-name: ${{ github.actor }} is generating new version 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - closed
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]
    env:
      lib_version: dfsf
      npm_token: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{env.npm_token}}
