name: Gitcook CI
run-name: ${{ github.actor }} is generating new version 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: pnpm build --if-present

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm pkg:release
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ env.github_token }}
          NODE_AUTH_TOKEN: ${{ env.npm_token }}
