name: Gitcook CI Release
run-name: ${{ github.actor }} is releasing new version 🚀
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm build

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm pkg:release
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ env.github_token }}
          NODE_AUTH_TOKEN: ${{ env.npm_token }}
